// Package maildev renders the maildev container command line from a
// profile's maildev.yaml. The lab's mail server is a receive-only sink:
// any flag that would make maildev relay or send mail outward is rejected
// here, before a container ever starts.
package maildev

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Container-internal listeners. Host ports are the profile's
// MAILDEV_SMTP_PORT / MAILDEV_WEB_PORT compose mappings.
const (
	SMTPPort = "1025"
	WebPort  = "1080"
)

// relayFlags would turn the sink into a relay / outbound sender. Rejected.
var relayFlags = map[string]string{
	"outgoing-host":    "configures an outgoing SMTP relay",
	"outgoing-port":    "configures an outgoing SMTP relay",
	"outgoing-user":    "configures an outgoing SMTP relay",
	"outgoing-pass":    "configures an outgoing SMTP relay",
	"outgoing-secure":  "configures an outgoing SMTP relay",
	"auto-relay":       "auto-forwards received mail outward",
	"auto-relay-rules": "auto-forwards received mail outward",
}

// managedFlags are owned by the lab, not the profile.
var managedFlags = map[string]string{
	"smtp":     "container-internal SMTP port is fixed; set MAILDEV_SMTP_PORT in profile.env for the host port",
	"web":      "container-internal web port is fixed; set MAILDEV_WEB_PORT in profile.env for the host port",
	"web-user": "web UI auth is generated by `mcplab secrets` (secrets/maildev-web-password), not stored in YAML",
	"web-pass": "web UI auth is generated by `mcplab secrets` (secrets/maildev-web-password), not stored in YAML",
}

type config struct {
	Flags map[string]any `yaml:"flags"`
}

// Args renders the full maildev argument string (compose splits it
// shell-style via the MAILDEV_ARGS interpolation). path may not exist;
// the base receive-only arguments are always emitted.
func Args(path string) (string, error) {
	args := []string{"--smtp", SMTPPort, "--web", WebPort}

	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return strings.Join(args, " "), nil
	}
	if err != nil {
		return "", err
	}
	var cfg config
	if err := yaml.Unmarshal(b, &cfg); err != nil {
		return "", fmt.Errorf("%s: %w", path, err)
	}

	keys := make([]string, 0, len(cfg.Flags))
	for k := range cfg.Flags {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		name := strings.TrimLeft(k, "-")
		if why, ok := relayFlags[name]; ok {
			return "", fmt.Errorf("%s: flag %q %s — this lab's mail server is receive-only", path, name, why)
		}
		if why, ok := managedFlags[name]; ok {
			return "", fmt.Errorf("%s: flag %q is managed by the lab: %s", path, name, why)
		}
		rendered, err := renderFlag(name, cfg.Flags[k])
		if err != nil {
			return "", fmt.Errorf("%s: %w", path, err)
		}
		args = append(args, rendered...)
	}
	return strings.Join(args, " "), nil
}

func renderFlag(name string, v any) ([]string, error) {
	flag := "--" + name
	switch val := v.(type) {
	case nil:
		return []string{flag}, nil
	case bool:
		if val {
			return []string{flag}, nil
		}
		return nil, nil
	case []any:
		out := []string{flag}
		for _, item := range val {
			s, err := scalar(name, item)
			if err != nil {
				return nil, err
			}
			out = append(out, s)
		}
		return out, nil
	default:
		s, err := scalar(name, v)
		if err != nil {
			return nil, err
		}
		return []string{flag, s}, nil
	}
}

func scalar(name string, v any) (string, error) {
	switch val := v.(type) {
	case string:
		if strings.ContainsAny(val, " \t\"'\n") {
			return "", fmt.Errorf("flag %q: value %q must not contain whitespace or quotes", name, val)
		}
		return val, nil
	case int, int64, float64:
		return fmt.Sprintf("%v", val), nil
	default:
		return "", fmt.Errorf("flag %q: unsupported value type %T", name, v)
	}
}
